name: web_scraping_telegram_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  televerse: ^3.0.1
  web_scraper: ^0.1.4
# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
